settings:  
    timezone: Asia/Makassar
database:  
    connection: mysql
    connections:
        mysql:
            driver: mysql
            host: localhost
            database: v2db
            username: fendi
            password: 
            charset: utf8
            collation: utf8_unicode_ci
            prefix: ''
            strict: false
base_url: 'http://localhost:8000/'            
